"""LLM WASM Sandbox - Production-grade security sandbox for untrusted Python code.

This package provides a secure execution environment for running untrusted Python code
generated by LLMs using WebAssembly (WASM) and WASI with the Wasmtime runtime.

Architecture
------------
The sandbox implements a multi-layer defense-in-depth security model:

1. **Core Layer** (core/): Type-safe models, base abstractions, and structured logging
   - ExecutionPolicy: Pydantic-validated configuration with secure defaults
   - SandboxResult: Typed execution results with metrics
   - BaseSandbox: Abstract interface for multi-runtime support
   - SandboxLogger: Structured event logging for observability

2. **Runtime Layer** (runtimes/): Runtime-specific sandbox implementations
   - PythonSandbox: CPython WASM execution with fuel/memory limits
   - (Future) JavaScriptSandbox: JavaScript runtime support

3. **Host Layer** (host.py): Low-level Wasmtime/WASI configuration
   - WASM binary loading and execution
   - Fuel budgeting and memory limiting
   - Capability-based filesystem isolation (WASI preopens)

Security Features
-----------------
- **Memory safety**: WASM sandboxing prevents buffer overflows and memory corruption
- **Capability-based I/O**: WASI restricts filesystem access to explicitly preopened
  directories (workspace only, mounted as /app in guest)
- **Fuel budgeting**: Deterministic instruction limits prevent infinite loops and
  excessive computation (configurable, default: 2B instructions)
- **Memory caps**: Prevents memory exhaustion attacks (default: 128 MB)
- **Output limiting**: Caps stdout/stderr to prevent log flooding
- **Policy validation**: Runtime validation of configuration using Pydantic

Quick Start
-----------
>>> from sandbox import create_sandbox, RuntimeType
>>> # All sandboxes are session-aware with auto-generated session IDs
>>> sandbox = create_sandbox(runtime=RuntimeType.PYTHON)
>>> print(sandbox.session_id)  # Auto-generated UUIDv4
'550e8400-e29b-41d4-a716-446655440000'
>>> result = sandbox.execute("print('Hello from WASM sandbox!')")
>>> print(result.stdout)
Hello from WASM sandbox!

>>> # Resume existing session
>>> sandbox = create_sandbox(session_id='550e8400-e29b-41d4-a716-446655440000')
>>> result = sandbox.execute("print('Continuing session')")

>>> # With custom policy
>>> from sandbox import ExecutionPolicy
>>> policy = ExecutionPolicy(fuel_budget=1_000_000_000, memory_bytes=64_000_000)
>>> sandbox = create_sandbox(policy=policy)

Exported API
------------
## Factory and Base Classes
- create_sandbox: Factory function for creating runtime-specific sandboxes
- BaseSandbox: Abstract base class for sandbox implementations
- PythonSandbox: Python WASM sandbox implementation

## Models and Types
- ExecutionPolicy: Pydantic model for validated execution configuration
- SandboxResult: Pydantic model for typed execution results
- RuntimeType: Enum for supported runtimes (PYTHON, JAVASCRIPT)

## Exceptions
- PolicyValidationError: Raised when policy configuration is invalid
- SandboxExecutionError: Raised when sandbox execution fails

## Logging
- SandboxLogger: Structured logger for sandbox events
"""

# Core models and types
# Base abstraction
from .core.base import BaseSandbox

# Exceptions
from .core.errors import PolicyValidationError, SandboxExecutionError

# Factory
from .core.factory import create_sandbox

# Logging
from .core.logging import SandboxLogger
from .core.models import ExecutionPolicy, RuntimeType, SandboxResult

# Storage adapters
from .core.storage import DiskStorageAdapter, StorageAdapter, StorageBackend

# Runtime implementations
from .runtimes.python.sandbox import PythonSandbox

# Session management
from .sessions import (
    PruneResult,
    SessionMetadata,
    delete_session_path,
    delete_session_workspace,
    list_session_files,
    prune_sessions,
    read_session_file,
    write_session_file,
)

__all__ = [
    "BaseSandbox",
    "DiskStorageAdapter",
    # Models and types
    "ExecutionPolicy",
    # Exceptions
    "PolicyValidationError",
    "PruneResult",
    "PythonSandbox",
    "RuntimeType",
    "SandboxExecutionError",
    # Logging
    "SandboxLogger",
    "SandboxResult",
    "SessionMetadata",
    # Storage adapters
    "StorageAdapter",
    "StorageBackend",
    # Factory and base
    "create_sandbox",
    # Session management (file operations and pruning)
    "delete_session_path",
    "delete_session_workspace",
    "list_session_files",
    "prune_sessions",
    "read_session_file",
    "write_session_file",
]
